### ISSUE TITLE
fix(shortcode): ensure that an anonymous donation hides donors name and not donation amount

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3603]
## User Story
As a site admin, I want donors that mark as anonymous to not be shown on the wall and only have the amount shown so that they will be anonymous.

## Current Behavior
I currently have the donation amount marked at zero, and the donor name still shows.

## Expected Behavior
I expect to have the anonymous donation be anonymous in donor name not donation amount.

## Steps to Reproduce
1. Make an anonymous donation
2. Setup a page with the Donor Wall
3. See that the amount is $0 and the donor name still shows

## Visuals
Making donation:
![screen shot 2018-08-14 at 5 58 44 pm](https://user-images.githubusercontent.com/20672471/44120892-db46e884-9feb-11e8-81df-4e27cb73d3df.png)

Shot of the Donor Wall:
![screen shot 2018-08-14 at 5 59 45 pm](https://user-images.githubusercontent.com/20672471/44120895-de0bb8c4-9feb-11e8-891f-09f3b23e9e67.png)

## Related
https://secure.helpscout.net/conversation/632665703/22737?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://givewp.gsamsmith.com
Site URL: https://givewp.gsamsmith.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wpk1_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewp.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.31
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2k
SUHOSIN Installed: –
MySQL Version: 5.6.40
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givewp.gsamsmith.com/donation-confirmation/
Failure Page: https://givewp.gsamsmith.com/donation-failed/
Donation History Page: https://givewp.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Stripe + Plaid, Test Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #370 ( N/A ) on 08/01/2018 at 07:25. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ✔ Licensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - AWeber: ✔ Licensed – by WordImpress – 1.0.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Constant Contact: ✔ Licensed – by WordImpress – 1.2.1
Give - ConvertKit: ✔ Licensed – by WordImpress – 1.0.2
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ✔ Licensed – by WordImpress – 1.2.2
Give - Dwolla Gateway: ✔ Licensed – by WordImpress – 1.1.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.7.1
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - GoCardless Gateway: ✔ Licensed – by WordImpress – 1.2
Give - Google Analytics Donation Tracking: ✔ Licensed – by WordImpress – 1.1.4
Give - iATS Payment Solutions: ✔ Licensed – by WordImpress – 1.0.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.6
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0
Give - PayUmoney: ❌ Unlicensed – by WordImpress – 1.0.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Per Form Gateways: ✔ Licensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.7.2
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.10
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Duplicator: by Snap Creek – 1.2.40
Give - Paymill Gateway: by WordImpress – 1.0.2
SG Optimizer: by SiteGround – 4.0.7
Transients Manager: by Pippin Williamson – 1.7.5
Wordfence Security: by Wordfence – 7.1.10
WP Rollback: by WordImpress – 1.5.1
WP Updates Notifier: by Scott Cariss – 1.4.4

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - Gift Aid: by WordImpress – 1.1.5
Give - Mollie Gateway: by WordImpress – 1.1.1

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
@samsmith89 According to the current logic anonymous donor will not show. This issue has been fixed. 

In addition, this functionality is not for dependent which can also create confusion to admin. I am creating a new issue for that.

**Comment by samsmith89** [comment]
Still isn't functioning. Here is a screencast, please let me know if I'm missing something:
https://screencast-o-matic.com/watch/cFQ6qtqGfU

Here's my local details:
<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, PayPal Standard, Test Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by WordImpress – 1.0.3
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.8.0
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0

### Other Active Plugins ###

Give - Fee Recovery: by GiveWP – 1.7.2
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - Stripe Gateway: by GiveWP – 2.1.0
Sam's Helper Function: by WordImpress – 1.0
WooCommerce: by Automattic – 3.4.5
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.0.0

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Duplicate Post: by Enrico Battocchi – 3.2.2
Indeed Ultimate Affiliate Pro: by indeed – 1.5
Mailgun: by Mailgun – 1.5.11
Page Builder by SiteOrigin: by SiteOrigin – 2.7.3
The7 Elements: by Dream-Theme – 1.11.0.1
The7 Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.16.24
ThemeREX Addons: by ThemeREX – 1.6.24
User Role Editor: by Vladimir Garagulya – 4.44
WooCommerce Paytm Payment Gateway: by Paytm – 0.2
WooCommerce Paytm Payment Gateway: by FTI Technologies – 1.0
WP Courseware: by Fly Plugins – 4.4.4
WPML Media: by OnTheGoSystems – 2.3.5
WPML Multilingual CMS: by OnTheGoSystems – 4.0.5
WPML Sticky Links: by OnTheGoSystems – 1.4.4
WPML String Translation: by OnTheGoSystems – 2.8.5
WPML Translation Management: by OnTheGoSystems – 2.6.5

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@samsmith89 Go to `shouldn't show` donor profile and check it is anonymous globally or not. Previously we are changing global anonymous donor meta on every donation which causes of the wrong output of donor wall on per-form basis because the donor can be anonymous for one form and non-anonymous for the second form. That's why we start saving donor as anonymous on per-form basis instead of editing donor global anonymous setting. You can still make donor anonymous global from donor profile page, but only admin can do that for now.

Check video in this pr: https://github.com/WordImpress/Give/pull/3657
